kind: Simple
apiVersion: k3d.io/v1alpha4
servers: 1
agents: 2
image: rancher/k3s:v1.23.6-k3s1
options:
  k3d:
    wait: true
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime: {}