# https://taskfile.dev

version: '3'

vars:
  CLUSTER_NAME: local

dotenv: ['.env']

tasks:
  install:
    desc: "Install/update tools"
    cmds:
      - brew install go-task/tap/go-task
      - brew install k3d
      - brew install derailed/k9s/k9s

  start:
    desc: "Start :allthethings:!"
    cmds:
      - task: k3d-cluster-create
      - task: bootstrap
      - task: k3d-cluster-configs

  k3d-cluster-create:
    desc: "Create k3d cluster."
    cmds:
      - k3d cluster create {{.CLUSTER_NAME}} --config ./k3d-config.yaml
      - kubectl get nodes

  k3d-cluster-delete:
    desc: "Clean up k3d cluster."
    cmds:
      - k3d cluster delete {{.CLUSTER_NAME}}

  k3d-cluster-configs:
    desc: "Get k3d cluster config."
    cmds:
      - k3d kubeconfig get {{.CLUSTER_NAME}}
  bootstrap:
    desc: "Bootstrap kubernetes"
    cmds:
      - task: bootstrap-argocd

  bootstrap-argocd:
    desc: "Bootstrap ArgoCD."
    cmds:
      - helm install argocd kubernetes/applications/argo/argocd --namespace argocd --create-namespace 
      - kubectl --namespace argocd delete secret -l owner=helm,name=argocd
      - kubectl apply --context k3d-{{.CLUSTER_NAME}} --namespace argocd -f kubernetes/bootstrap/homelab.yaml
